### ISSUE TITLE
Swift 3.0 Compatibility

### ISSUE THREAD

**Issue by damianesteban** [thoughtbot/Delta#40]
Is an update for Swift 3.0 on the horizon?  I started using Delta recently with RAC and I really like it.

**Comment by jakecraige** [comment]
Great to hear you're using it and liking it!

There hasn't been any work to upgrade to Swift 3 yet, but we definitely should.

I have a project that's using Delta and plan to upgrade the project to Swift 3 soon, so upgrading Delta would be part of that. I'm thinking I'll probably get to it this week, but would also happily accept a PR if you're interested in doing it.

**Comment by damianesteban** [comment]
Sounds good.  I'll take a look tomorrow and see what I can do.

**Comment by jakecraige** [comment]
Sweet, I had some time this morning so I pushed up a branch, https://github.com/thoughtbot/Delta/tree/swift3, working on upgrading many other deps too so I haven't fully tested it but it probably will(might) work

**Comment by damianesteban** [comment]
No issues on my end so far.  I'm going to build out this project I'm working on a bit more tomorrow and we'll see.  Thank you.
