### ISSUE TITLE
swift-3.0 branch

### ISSUE THREAD

**Issue by ghost** [thoughtbot/Delta#42]
Hi, I am trying to add this Delta branch to a Swift 3 project I am working on.
The Delta.framework is linked in the project and is seen where 'imported'.

What occurs though is when I attempt to build and run to the Simulator.
Up to now, my project ran on the Simulator with no warnings or errors.

The compiler error I get is:
`dyld: Library not loaded: @rpath/Delta.framework/Delta
  Referenced from: /Users/mikenorman/Library/Developer/CoreSimulator/Devices/1EB55262-AAA4-41D4-892A-7E958D1CB515/data/Containers/Bundle/Application/836A24C4-D6AF-4900-92B6-9722B998F615/trips.app/trips
  Reason: image not found
(lldb) `

Any idea of what might be causing this? I am also looking on Stackoverflow for similar issues.

Thanks

--mike

**Comment by eliperkins** [comment]
Are you using Carthage to build your dependencies? If so, it sounds like you're missing the [`carthage copy-frameworks` setup in your Xcode project](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos). This will ensure that the frameworks are properly loaded into your binary at build time.

**Comment by ghost** [comment]
Hi Eli.

Thanks for that suggestion.

No, I'm not using Carthage, I built the framework from the Xcode project only. I have solved that small issue now by adding the framework to the Embedded Binaries, duh!

Now I am working on getting one view controller to subscribe to a Boolean action dispatched from another view controller, which isn't behaving. I'll look at the DeltaTodoExample for some ideas.

Currently I am on Xcode 8.0, Swift 3.0, and the iOS 10.0 SDK.

Thanks for your help.

--mike
